<?php
/**
 * Created by PhpStorm.
 * User: dougl
 * Date: 23/10/2017
 * Time: 18:55
 */




//CONSTANTES QUE O PHP JA POSSUI NATIVAMENTE


echo PHP_VERSION;

echo "<br/>";

echo DIRECTORY_SEPARATOR; // BARRA DE DIRETORIO NO WINDOWS, NO LINUX É AO CONTRARIO. CASO DESENVOLVA NO WINDOWS E O SERVIDOR FOR O LINUX USA-SE ESSA CONSTANTE PARA INVERTER A BARRA

